options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1) Build imagen desde Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}',
    '.'
  ]

# 2) Push imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'
  ]

# 3) Deploy a Cloud Run con configuración actualizada
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_CLOUD_RUN_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
    - --region=${_REGION}
    - --platform=managed
    - --service-account=${_CLOUD_RUN_SA}
    - --vpc-connector=${_VPC_CONNECTOR}
    - --vpc-egress=private-ranges-only
    - --set-env-vars=DB_USER=psqladm,DB_NAME=retoqueplan,DB_PORT=5432,NODE_ENV=production
    - --set-secrets=DATABASE_URL=database_url:latest,DB_PASSWORD=db-credentials:latest
    - --allow-unauthenticated
    - --port=3000

substitutions:
  _REGION: "us-central1"
  _REPO_NAME: "app-repo"
  _CLOUD_RUN_SERVICE: "backend-service"
  _CLOUD_RUN_SA: "queplan-backend-sa@${PROJECT_ID}.iam.gserviceaccount.com"
  _VPC_CONNECTOR: "projects/${PROJECT_ID}/locations/us-central1/connectors/queplan-vpc-connector"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'

timeout: '1200s'
