options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1) Build imagen desde Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}',
    '.'
  ]

# 2) Push imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'
  ]

# 3) Deploy a Cloud Run (egress privado hacia VPC para AlloyDB)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_CLOUD_RUN_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}
    - --region=${_REGION}
    - --platform=managed
    - --service-account=${_CLOUD_RUN_SA}
    - --vpc-connector=${_VPC_CONNECTOR}
    - --vpc-egress=private-ranges-only
    - --set-secrets=DB_CONFIG=db-credentials:latest
    - --allow-unauthenticated

substitutions:
  _REGION: "us-central1"
  _REPO_NAME: "app-repo"
  _CLOUD_RUN_SERVICE: "backend-service"
  _CLOUD_RUN_SA: "cloud-run-runtime@${PROJECT_ID}.iam.gserviceaccount.com"
  _VPC_CONNECTOR: "projects/${PROJECT_ID}/locations/us-central1/connectors/serverless-conn"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'

timeout: '1200s'
