options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: hashicorp/terraform:1.5.7
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Iniciando Terraform ==="
        terraform init
        terraform apply -auto-approve \
          -var-file="terraform.tfvars"
        echo "=== Terraform finalizado ==="

timeout: 1200s
