options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Terraform - Infraestructura
  - name: hashicorp/terraform:1.5.7
    entrypoint: sh
    args:
      - -c
      - |
        echo "=== Iniciando Terraform ==="
        terraform init
        terraform apply -auto-approve \
          -var-file="terraform.tfvars"
        echo "=== Terraform finalizado ==="

  # 2️⃣ Construir imagen Backend
  - name: gcr.io/cloud-builders/docker
    dir: ../backend
    args:
      [
        "build", 
        "-t", "us-central1-docker.pkg.dev/queplan-468417/backend/backend:latest", 
        "."
      ]

  # 3️⃣ Subir imagen Backend a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/queplan-468417/backend/backend:latest"]

  # 4️⃣ Desplegar Backend en Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "backend",
        "--image=us-central1-docker.pkg.dev/queplan-468417/backend/backend:latest",
        "--service-account=backend-sa@queplan-468417.iam.gserviceaccount.com",
        "--set-secrets=DB_PASSWORD=db-password:latest",
        "--region=us-central1",
        "--allow-unauthenticated"
      ]

  # 5️⃣ Construir imagen Frontend con API_URL del backend
  - name: gcr.io/cloud-builders/docker
    dir: ../frontend
    args:
      [
        "build",
        "--build-arg", "API_URL=$(gcloud run services describe backend --region=us-central1 --format='value(status.url)')/api",
        "-t", "us-central1-docker.pkg.dev/queplan-468417/frontend/frontend:latest",
        "."
      ]

  # 6️⃣ Subir imagen Frontend a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/queplan-468417/frontend/frontend:latest"]

  # 7️⃣ Desplegar Frontend en Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "frontend",
        "--image=us-central1-docker.pkg.dev/queplan-468417/frontend/frontend:latest",
        "--region=us-central1",
        "--allow-unauthenticated"
      ]

timeout: 1800s
